# Generated by Django 4.2 on 2023-05-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chovatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno musí být vyplněno'}, help_text='Zadejte jméno', max_length=80, verbose_name='Jméno')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení musí být vyplněno'}, help_text='Zadejte příjmení autora', max_length=50, verbose_name='Příjmení autora')),
                ('telefon', models.CharField(blank=True, help_text='Zadejte telefon v podobě: +420 777 777 777', max_length=16, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Chovatel',
                'verbose_name_plural': 'Chovatele',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Oceneni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('druh_oceneni', models.CharField(help_text='Zadejte druh oceneni', max_length=20, verbose_name='Druh oceneni')),
            ],
            options={
                'verbose_name': 'Oceneni',
                'verbose_name_plural': 'Oceneni',
                'ordering': ['druh_oceneni'],
            },
        ),
        migrations.CreateModel(
            name='Zvire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('druh_zvirete', models.CharField(error_messages={'blank': 'Druh musí být vyplněn'}, help_text='Zadejte Druh zvirete', max_length=100, verbose_name='Druh zvirete')),
                ('chovatel', models.ManyToManyField(to='myapp.chovatel')),
                ('oceneni', models.ManyToManyField(to='myapp.oceneni')),
            ],
            options={
                'verbose_name': 'Druh Zvirete',
                'verbose_name_plural': 'Druhy Zvirat',
                'ordering': ['druh_zvirete'],
            },
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
